### ISSUE TITLE
Cannot find module iconv.node (on osx)

### ISSUE THREAD

**Issue by inovek** [alexander-heimbuch/linguee-alfred-workflow#1]
I've tried to install iconv globally but that' don't works. Do I've to install it into the workflow folder? (a little bit confused because there is already the iconv)

> [ERROR: alfred.workflow.input.scriptfilter] Code 1: module.js:338
    throw err;
          ^
Error: Cannot find module '../build/Debug/iconv.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/USERNAME/Dropbox/Sync/Applications/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FF5CD685-26B2-495B-B9CA-2DFF5E9732B9/node_modules/iconv/lib/iconv.js:29:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
[ERROR: alfred.workflow.input.scriptfilter] Code 1: module.js:338
    throw err;
          ^
Error: Cannot find module '../build/Debug/iconv.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/USERNAME/Dropbox/Sync/Applications/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FF5CD685-26B2-495B-B9CA-2DFF5E9732B9/node_modules/iconv/lib/iconv.js:29:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
[ERROR: alfred.workflow.input.scriptfilter] Code 1: module.js:338
    throw err;
          ^
Error: Cannot find module '../build/Debug/iconv.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/USERNAME/Dropbox/Sync/Applications/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FF5CD685-26B2-495B-B9CA-2DFF5E9732B9/node_modules/iconv/lib/iconv.js:29:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by alexander-heimbuch** [comment]
Hey,
sorry for the late response. Could you give me your installed node version?

**Comment by inovek** [comment]
Greetings, "node -v" returns "v0.12.7".

**Comment by alexander-heimbuch** [comment]
You should update Node at least to 4.0

**Comment by inovek** [comment]
I've uninstalled node 0.12.7 via console and installed "node 4.4.3" via package. (installer for osx)
Installed iconv via "sudo npm install iconv -g", installed dependencies (like xcode + agreeing terms, node-gyp for configure & build)

**But it seems the error is the same:**

> `[ERROR: alfred.workflow.input.scriptfilter] Code 1: module.js:327
>     throw err;
>     ^
> 
> Error: Cannot find module '../build/Debug/iconv.node'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/Users/USERNAME/Dropbox/Backups/Anwendungen/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FF5CD685-26B2-495B-B9CA-2DFF5E9732B9/node_modules/iconv/lib/iconv.js:29:14)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
> [ERROR: alfred.workflow.input.scriptfilter] Code 1: module.js:327
>     throw err;
>     ^
> 
> Error: Cannot find module '../build/Debug/iconv.node'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/Users/USERNAME/Dropbox/Backups/Anwendungen/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FF5CD685-26B2-495B-B9CA-2DFF5E9732B9/node_modules/iconv/lib/iconv.js:29:14)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
> [ERROR: alfred.workflow.input.scriptfilter] Code 1: module.js:327
>     throw err;
>     ^
> 
> Error: Cannot find module '../build/Debug/iconv.node'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/Users/USERNAME/Dropbox/Backups/Anwendungen/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FF5CD685-26B2-495B-B9CA-2DFF5E9732B9/node_modules/iconv/lib/iconv.js:29:14)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)`

I think I missing something or did something wrong.
Node is new ground for me, until yet I only used it for code minifiers.

**Comment by inovek** [comment]
Fixed it by execute "node-gyp configure" and "node-gyp build" in the iconv directory of this workflow.

Tested you workflow and have to say: "Thank you for your great effort to make linguee so fast accessable. I use this page very often and with this... wow!"

Good Work!

**Comment by alexander-heimbuch** [comment]
Hey,
thanks for sharing your solution. Good to hear that is useful for others as well :) Maybe I will implement it in ruby if Alfred 3 is released to avoid runtime environment issues with node.

**Comment by inovek** [comment]
Good idea, but I think this shouldn't become an issue. Wouldn't be your workflow slows down a bit if you port it to Ruby? I think node related issues should be documented into a wiki page. People (like me) have to learn to work more with node, too. (now and in the future it will become more and more relevance and dependence for us all)

**Comment by alexander-heimbuch** [comment]
I don't think that this will slow down the workflow. Maybe implementing it in go would be another good solution. Regarding your suggestion, could you create a dedicated improvement issue so we can work on that?
